Update push2QGG.yml

diff --git a/.github/workflows/push2QGG.yml b/.github/workflows/push2QGG.yml
--- a/.github/workflows/push2QGG.yml
+++ b/.github/workflows/push2QGG.yml
@@ -1,11 +1,11 @@
-name: Push to QGG-Computational-Statistics
+name: Sync Personal to Organization
 on:
   push:
     branches: [ main ]
   workflow_dispatch:
 
 jobs:
-  push-to-org:
+  sync:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout personal repository
@@ -18,10 +18,16 @@ jobs:
           git config --global user.email "bjarke.poulsen@pm.me"
           git config --global user.name "BgroveP"
 
-      - name: Push changes to organization repository
+      - name: Add organization repository as remote with PAT
         run: |
           git remote add org https://x-access-token:${{ secrets.QGG_PAT }}@github.com/QGG-Computational-Statistics/LocalAncestry.jl.git
+
+      - name: Fetch and merge changes from organization
+        run: |
           git fetch org
           git checkout main
-          git merge org/main --no-edit -X theirs  # Prefer their changes if conflicts
+          git merge org/main --no-edit -X theirs || true  # Continue even if merge fails
+
+      - name: Push changes to organization repository
+        run: |
           git push https://x-access-token:${{ secrets.QGG_PAT }}@github.com/QGG-Computational-Statistics/LocalAncestry.jl.git main
